name: Yardang Build
description: 'Install, build, and deploy Sphinx documentation with Yardang'

inputs:
  token:
    type: string
    description: "GitHub Token"
    required: true
  version:
    type: choice
    description: "Python version to install"
    options:
      - '3.9'
      - '3.10'
      - '3.11'
      - '3.12'
      - '3.13'
    default: '3.9'
  install_path:
    type: string
    description: "Path to project to install"
    default: '.'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.version }}
        cache: "pip"
        cache-dependency-path: |
          "**/pyproject.toml"
          "**/setup.py"
    - run: pip install ${{ inputs.install_path }}
      shell: bash
    - run: yardang build
      shell: bash
    - uses: peaceiris/actions-gh-pages@v4
      with:
        publish_branch: gh-pages
        github_token: ${{ inputs.token }}
        publish_dir: docs/html
        force_orphan: true
